---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: warc-solr
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  selector:
    app: zookeeper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-data-pvc
  namespace: warc-solr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-datalog-pvc
  namespace: warc-solr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: warc-solr
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.8
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOO_MY_ID
          value: "1"
        - name: ZOO_SERVERS
          value: "server.1=0.0.0.0:2888:3888;2181"
        - name: ZOO_4LW_COMMANDS_WHITELIST
          value: "mntr,conf,ruok"
        volumeMounts:
        - name: zk-data
          mountPath: /data
        - name: zk-datalog
          mountPath: /datalog
        readinessProbe:
          tcpSocket:
            port: 2181
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 2181
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: zk-data
        persistentVolumeClaim:
          claimName: zk-data-pvc
      - name: zk-datalog
        persistentVolumeClaim:
          claimName: zk-datalog-pvc

